title:              Predictive Perception
email:              sebastian.m.englert@gmail.com
description:        A Digital Portfolio and Blog by Sebastian Englert
author:             Sebastian Englert
baseurl:            "/"
url:                "https://predictiveperception.com"

# Social Profiles
github_username:    see-bass
linkedin_username:  sebastianenglert

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
